=== navikt/fp-dokgen/content/templates/klage-hjemsendt/schema.json
{
  "$id": "klage-hjemsendt",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "Dokumentdata for brev klage hjemsendt",
  "type": "object",
  "required": [
    "felles",
    "gjelderTilbakekreving",
    "opphevet",
    "ettersendelsesfrist"
  ],
  "properties": {
    "felles": {
      "$ref": "file:content/templates/schema_felles.json"
    },
    "gjelderTilbakekreving": {
      "type": "boolean"
    },
    "opphevet": {
      "type": "boolean"
    },
    "ettersendelsesfrist": {
      "type": "string"
    }
  }
}

=== navikt/fp-dokgen/content/templates/klage-hjemsendt/testdata/test_fp_opphevet_tilbakekreving.json
{
  "felles": {
    "søkerNavn": "Dolly Duck",
    "søkerPersonnummer": "300220 12345",
    "fritekst": "FRITEKST",
    "brevDato": "4. mai 2021",
    "erAutomatiskBehandlet": false,
    "saksnummer": "123456789",
    "ytelseType": "FP",
    "behandlesAvKA": true,
    "erUtkast": false
  },
  "gjelderTilbakekreving": true,
  "opphevet": true,
  "ettersendelsesfrist": "14. juni 2021"
}
