=== navikt/fp-dokgen/content/templates/engangsstonad-avslag/schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "object",
  "title": "The Root Schema",
  "required": [
    "felles",
    "avslagÅrsak",
    "førstegangsbehandling",
    "antallBarn",
    "relasjonsRolle",
    "gjelderFødsel",
    "vilkårTyper",
    "klagefristUker"
  ],
  "properties": {
    "felles": {
      "type": "object"
    },
    "avslagÅrsak": {
      "type": "string"
    },
    "førstegangsbehandling": {
      "type": "boolean"
    },
    "antallBarn": {
      "type": "number"
    },
    "relasjonsRolle": {
      "type": "string"
    },
    "gjelderFødsel": {
      "type": "boolean"
    },
    "vilkårTyper": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "klagefristUker": {
      "type": "number"
    },
    "avslagMedlemskap": {
      "type": "string"
    }
  }
}

=== navikt/fp-dokgen/content/templates/engangsstonad-avslag/testdata/test_avslag_fb.json
{
  "felles": {
    "søkerNavn": "Dolly Duck",
    "søkerPersonnummer": "300220 12345",
    "brevDato": "4. april 2020",
    "saksnummer": "123456789",
    "mottakerNavn": "Finn Verge",
    "fritekst": "Du har ikke gitt dokumentasjon om hvorfor du søkte for sent",
    "erUtkast": false
  },
  "avslagÅrsak": "SØKT_FOR_SENT",
  "førstegangsbehandling": true,
  "antallBarn": 1,
  "relasjonsRolle": "MORA",
  "gjelderFødsel": false,
  "vilkårTyper": ["FP_VK_3"],
  "klagefristUker": 6
}

=== navikt/fp-dokgen/content/templates/engangsstonad-avslag/testdata/test_avslag_rv.json
{
  "felles": {
    "søkerNavn": "Dolly Duck",
    "søkerPersonnummer": "300220 12345",
    "brevDato": "4. april 2020",
    "saksnummer": "123456789",
    "behandlesAvKA": false,
    "erUtkast": false
  },
  "avslagÅrsak": "MOR_IKKE_DØD_VED_FØDSEL_OMSORG",
  "førstegangsbehandling": false,
  "antallBarn": 0,
  "relasjonsRolle": "FARA",
  "gjelderFødsel": true,
  "vilkårTyper": ["FP_VK_3"],
  "klagefristUker": 6,
  "avslagMedlemskap": "IKKE_MEDL_ETTER_FØDSEL"
}
