=== navikt/fp-dokgen/src/main/resources/content/templates/innhente-opplysninger/schema.json
{
  "$id": "urn:no:nav:fpdokgen:innhente-opplysninger",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "Dokumentdata for brev Innhente opplysninger",
  "type": "object",
  "required": [
    "felles",
    "førstegangsbehandling",
    "revurdering",
    "endringssøknad",
    "død",
    "klage"
  ],
  "properties": {
    "felles": {
      "$ref": "classpath:content/templates/schema_felles.json"
    },
    "førstegangsbehandling": {
      "type": "boolean"
    },
    "revurdering": {
      "type": "boolean"
    },
    "endringssøknad": {
      "type": "boolean"
    },
    "død": {
      "type": "boolean"
    },
    "klage": {
      "type": "boolean"
    },
    "søknadDato": {
      "type": "string"
    },
    "fristDato": {
      "type": "string"
    }
  }
}

=== navikt/fp-dokgen/content/templates/innhente-opplysninger/testdata/test_es_fgb_død.json
{
  "felles": {
    "søkerNavn": "Dolly Duck",
    "søkerPersonnummer": "300220 12345",
    "fritekst": "Tekst\n- Attest\n- Bekreftelse\nMer tekst",
    "brevDato": "4. april 2020",
    "erKopi": false,
    "harVerge": false,
    "saksnummer": "123456789",
    "ytelseType": "ES",
    "erUtkast": false
  },
  "førstegangsbehandling": true,
  "revurdering": false,
  "endringssøknad": false,
  "død": true,
  "klage": false,
  "søknadDato": "1. april 2020",
  "fristDato": "24. mai 2020"
}

=== navikt/fp-dokgen/content/templates/innhente-opplysninger/testdata/test_svp_fgb.json
{
  "felles": {
    "søkerNavn": "Dolly Duck",
    "søkerPersonnummer": "300220 12345",
    "fritekst": "Tekst\n- Attest\n- Bekreftelse\nMer tekst",
    "brevDato": "4. april 2020",
    "erKopi": false,
    "harVerge": false,
    "saksnummer": "123456789",
    "ytelseType": "SVP",
    "erUtkast": false
  },
  "førstegangsbehandling": true,
  "revurdering": false,
  "endringssøknad": false,
  "død": false,
  "klage": false,
  "søknadDato": "1. april 2020",
  "fristDato": "24. mai 2020"
}

=== navikt/fp-dokgen/content/templates/innhente-opplysninger/testdata/test_fp_endringssøknad.json
{
  "felles": {
    "søkerNavn": "Dolly Duck",
    "søkerPersonnummer": "300220 12345",
    "fritekst": "Tekst\n- Attest\n- Bekreftelse\nMer tekst",
    "brevDato": "4. april 2020",
    "erKopi": false,
    "harVerge": false,
    "saksnummer": "123456789",
    "ytelseType": "FP",
    "behandlesAvKA": false
  },
  "førstegangsbehandling": false,
  "revurdering": true,
  "endringssøknad": true,
  "død": false,
  "klage": false,
  "søknadDato": "1. april 2020",
  "fristDato": "24. mai 2020"
}
