=== navikt/fp-dokgen/content/templates/henleggelse/schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "object",
  "title": "The Root Schema",
  "required": [
    "felles",
    "vanligBehandling",
    "klage",
    "anke",
    "innsyn"
  ],
  "properties": {
    "felles": {
      "type": "object"
    },
    "vanligBehandling": {
      "type": "boolean"
    },
    "klage": {
      "type": "boolean"
    },
    "anke": {
      "type": "boolean"
    },
    "innsyn": {
      "type": "boolean"
    },
    "opphavType": {
      "type": "string"
    }
  }
}

=== navikt/fp-dokgen/content/templates/henleggelse/testdata/test_henleggelse_innsyn.json
{
  "felles": {
    "søkerNavn": "Dolly Duck",
    "søkerPersonnummer": "300220 12345",
    "brevDato": "4. april 2020",
    "saksnummer": "123456789",
    "ytelseType": "ES",
    "behandlesAvKA": false,
    "erUtkast": false
  },
  "vanligBehandling": false,
  "klage": false,
  "anke": false,
  "innsyn": true,
  "opphavType": "FAMPEN"
}

=== navikt/fp-dokgen/content/templates/henleggelse/testdata/test_henleggelse_vanligBehandling.json
{
  "felles": {
    "søkerNavn": "Dolly Duck",
    "søkerPersonnummer": "300220 12345",
    "brevDato": "4. april 2020",
    "saksnummer": "123456789",
    "ytelseType": "FP",
    "behandlesAvKA": false,
    "erUtkast": false
  },
  "vanligBehandling": true,
  "klage": false,
  "anke": false,
  "innsyn": false,
  "opphavType": "FAMPEN"
}

=== navikt/fp-dokgen/content/templates/henleggelse/testdata/test_henleggelse_klage.json
{
  "felles": {
    "søkerNavn": "Dolly Duck",
    "søkerPersonnummer": "300220 12345",
    "brevDato": "4. april 2020",
    "saksnummer": "123456789",
    "ytelseType": "SVP",
    "behandlesAvKA": false
  },
  "vanligBehandling": false,
  "klage": true,
  "anke": false,
  "innsyn": false,
  "opphavType": "KLAGE"
}
