=== navikt/fp-dokgen/content/templates/etterlys-inntektsmelding/schema.json
{
  "$id": "etterlys-inntektsmelding",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "Dokumentdata for brev etterlys inntektsmelding",
  "type": "object",
  "required": [
    "felles",
    "søknadDato",
    "antallIkkeMottattIM",
    "antallMottattIM",
    "inntektsmeldingerStatus"
  ],
  "$defs": {
    "arbeidsforholdInntektsmelding": {
      "type": "object",
      "required": [
        "arbeidsgiverIdent",
        "arbeidsgiverNavn",
        "stillingsprosent",
        "erInntektsmeldingMottatt"
      ],
      "properties": {
        "arbeidsgiverIdent": {
          "type": "string"
        },
        "arbeidsgiverNavn": {
          "type": "string"
        },
        "stillingsprosent": {
          "type": "number"
        },
        "erInntektsmeldingMottatt": {
          "type": "boolean"
        }
      }
    }
  },
  "properties": {
    "felles": {
      "$ref": "file:content/templates/schema_felles.json"
    },
    "søknadDato": {
      "type": "string"
    },
    "antallIkkeMottattIM": {
      "type": "number"
    },
    "antallMottattIM": {
      "type": "number"
    },
    "inntektsmeldingerStatus": {
      "type": "array",
      "items": { "$ref": "#/$defs/arbeidsforholdInntektsmelding" }
    }
  }
}

=== navikt/fp-dokgen/content/templates/etterlys-inntektsmelding/testdata/test_svp.json
{
  "felles": {
    "søkerNavn": "Dolly Duck",
    "søkerPersonnummer": "300220 12345",
    "brevDato": "4. april 2020",
    "erKopi": false,
    "harVerge": false,
    "saksnummer": "123456789",
    "ytelseType": "SVP",
    "erUtkast": false
  },
  "søknadDato": "1. april 2020",
  "antallIkkeMottattIM": 1,
  "antallMottattIM": 1,
  "inntektsmeldingerStatus": [
    {
      "arbeidsgiverIdent": "123456789",
      "arbeidsgiverNavn": "Andeby Bank AS",
      "stillingsprosent": 80.0,
      "erInntektsmeldingMottatt": false
    },
    {
      "arbeidsgiverIdent": "99999998",
      "arbeidsgiverNavn": "Andeby Vaktmester AS",
      "stillingsprosent": 20.0,
      "erInntektsmeldingMottatt": true
    }
  ]
}

=== navikt/fp-dokgen/content/templates/etterlys-inntektsmelding/testdata/test_fp.json
{
  "felles": {
    "søkerNavn": "Dolly Duck",
    "søkerPersonnummer": "300220 12345",
    "brevDato": "4. april 2020",
    "erKopi": false,
    "harVerge": false,
    "saksnummer": "123456789",
    "ytelseType": "FP",
    "erUtkast": false
  },
  "søknadDato": "1. april 2020",
    "antallIkkeMottattIM": 2,
    "antallMottattIM": 2,
    "inntektsmeldingerStatus":[    {
      "arbeidsgiverIdent": "123456789",
      "arbeidsgiverNavn": "Andeby Bank AS",
      "stillingsprosent": 80,
      "erInntektsmeldingMottatt":false
    },
      {
        "arbeidsgiverIdent": "99999999",
        "arbeidsgiverNavn": "Andeby Vask AS",
        "stillingsprosent": 10,
        "erInntektsmeldingMottatt":false
      },
      {
        "arbeidsgiverIdent": "99999998",
        "arbeidsgiverNavn": "Andeby Vaktmester AS",
        "stillingsprosent": 5,
        "erInntektsmeldingMottatt":true
      },
      {
        "arbeidsgiverIdent": "99999997",
        "arbeidsgiverNavn": "Andeby Service AS",
        "stillingsprosent": 5,
        "erInntektsmeldingMottatt":true
      }
    ]
}
