=== navikt/fp-dokgen/src/main/resources/content/templates/klage-avvist/schema.json
{
  "$id": "urn:no:nav:fpdokgen:klage-avvist",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "description": "Dokumentdata for brev klage avvist",
  "type": "object",
  "required": [
    "felles",
    "gjelderTilbakekreving",
    "lovhjemler",
    "klagefristUker",
    "avvistGrunner",
    "påklagdVedtak"
  ],
  "properties": {
    "felles": {
      "$ref": "classpath:content/templates/schema_felles.json"
    },
    "gjelderTilbakekreving": {
      "type": "boolean"
    },
    "lovhjemler": {
      "type": "string"
    },
    "klagefristUker": {
      "type": "number"
    },
    "avvistGrunner": {
      "type": "array",
      "items": { "type": "string" }
    },
    "påklagdVedtak": {
      "type": "boolean"
    }
  }
}

=== navikt/fp-dokgen/content/templates/klage-avvist/testdata/test_paklagd_vedtak.json
{
  "felles": {
    "søkerNavn": "Dolly Duck",
    "søkerPersonnummer": "300220 12345",
    "brevDato": "4. mai 2021",
    "erAutomatiskBehandlet": false,
    "saksnummer": "123456789",
    "ytelseType": "FP",
    "erUtkast": false
  },
  "gjelderTilbakekreving": false,
  "lovhjemler": "folketrygdloven § 21-12 og forvaltningsloven §§ 28, 31, 32 og 34",
  "klagefristUker": 6,
  "avvistGrunner": [
    "KLAGE_UGYLDIG"
  ],
  "påklagdVedtak": true
}
