=== navikt/fp-dokgen/content/templates/forlenget-saksbehandlingstid/schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "object",
  "title": "The Root Schema",
  "required": [
    "felles",
    "variantType",
    "død",
    "behandlingsfristUker",
    "antallBarn"
  ],
  "properties": {
    "felles": {
      "type": "object"
    },
    "variantType": {
      "type": "string"
    },
    "død": {
      "type": "boolean"
    },
    "behandlingsfristUker": {
      "type": "number"
    },
    "antallBarn": {
      "type": "number"
    }
  }
}

=== navikt/fp-dokgen/content/templates/forlenget-saksbehandlingstid/testdata/test_fp_KLAGE_død.json
{
  "felles": {
    "søkerNavn": "Dolly Duck",
    "søkerPersonnummer": "300220 12345",
    "fritekst" : "FRITEKST",
    "brevDato": "4. april 2020",
    "erKopi" : false,
    "harVerge" : false,
    "saksnummer" : "123456789",
    "ytelseType" : "FP"
  },
  "variantType": "KLAGE",
  "død": true,
  "behandlingsfristUker": 5,
  "antallBarn": 1
}

=== navikt/fp-dokgen/content/templates/forlenget-saksbehandlingstid/testdata/test_fp_FORLENGET_død.json
{
  "felles": {
    "søkerNavn": "Dolly Duck",
    "søkerPersonnummer": "300220 12345",
    "fritekst": "FRITEKST",
    "brevDato": "4. april 2020",
    "erKopi": false,
    "harVerge": false,
    "saksnummer": "123456789",
    "ytelseType": "FP",
    "behandlesAvKA": false
  },
  "variantType": "FORLENGET",
  "død": true,
  "behandlingsfristUker": 5,
  "antallBarn": 1
}

=== navikt/fp-dokgen/content/templates/forlenget-saksbehandlingstid/testdata/test_es_FORLENGET.json
{
  "felles": {
    "søkerNavn": "Dolly Duck",
    "søkerPersonnummer": "300220 12345",
    "fritekst": "FRITEKST",
    "brevDato": "4. april 2020",
    "erKopi": false,
    "harVerge": false,
    "saksnummer": "123456789",
    "ytelseType": "ES",
    "behandlesAvKA": false,
    "erUtkast": false
  },
  "variantType": "FORLENGET",
  "død": false,
  "behandlingsfristUker": 5,
  "antallBarn": 1
}

=== navikt/fp-dokgen/content/templates/forlenget-saksbehandlingstid/testdata/test_fp_KLAGE.json
{
  "felles": {
    "søkerNavn": "Dolly Duck",
    "søkerPersonnummer": "300220 12345",
    "fritekst": "FRITEKST",
    "brevDato": "4. april 2020",
    "erKopi": false,
    "harVerge": false,
    "saksnummer": "123456789",
    "ytelseType": "FP",
    "erUtkast": false
  },
  "variantType": "KLAGE",
  "død": false,
  "behandlingsfristUker": 5,
  "antallBarn": 1
}
