=== navikt/fp-dokgen/content/templates/svangerskapspenger-opphor/schema.json
{
  "$id": "svangerskapspenger-opphor",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "Dokumentdata for brev Svangerskapspenger Opphør",
  "type": "object",
  "required": [
    "felles",
    "lovhjemmel",
    "erSøkerDød",
    "opphørtPeriode"
  ],
  "$defs": {
    "opphørPeriode": {
      "type": "object",
      "required": [
        "årsak",
        "antallArbeidsgivere"
      ],
      "properties": {
        "årsak": {
          "type": "string"
        },
        "stønadsperiodeFom": {
          "type": "string"
        },
        "stønadsperiodeTom": {
          "type": "string"
        },
        "antallArbeidsgivere": {
          "type": "number"
        }
      }
    }
  },
  "properties": {
    "felles": {
      "$ref": "file:content/templates/schema_felles.json"
    },
    "opphørsdato": {
      "type": "string"
    },
    "erSøkerDød": {
      "type": "boolean"
    },
    "dødsdatoBarn": {
      "type": "boolean"
    },
    "fødselsdato": {
      "type": "string"
    },
    "halvG": {
      "type": "number"
    },
    "lovhjemmel": {
      "type": "string"
    },
    "opphørtPeriode": {
      "type": "object",
      "items": { "$ref": "#/$defs/opphørPeriode" }
    },
    "klagefristUker": {
      "type": "number"
    }
  }
}

=== navikt/fp-dokgen/content/templates/svangerskapspenger-opphor/testdata/medl_1024.json
{
  "felles": {
    "søkerNavn": "Dolly Duck",
    "søkerPersonnummer": "300220 12345",
    "brevDato": "4. mai 2021",
    "erAutomatiskBehandlet": true,
    "saksnummer": "123456789",
    "erUtkast": false
  },
  "opphørsdato": "4. mai 2021",
  "erSøkerDød": false,
  "halvG": 50000,
  "lovhjemmel":"§ 14-4 og § forvaltningsloven § 35",
  "klagefristUker": 6,
  "opphørtPeriode":
    {
      "årsak": "1024",
      "antallArbeidsgivere": 1
    }
}
