=== navikt/fp-dokgen/content/templates/svangerskapspenger-innvilgelse/schema.json
{
  "$id": "svangerskapspenger-innvilgelse",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "Dokumentdata for brev svangerskapspenger innvilgelse",
  "type": "object",
  "required": [
    "felles",
    "revurdering",
    "endretFraAvslag",
    "utbetalingEndret",
    "termindatoEndret",
    "refusjonTilBruker",
    "antallRefusjonerTilArbeidsgivere",
    "månedsbeløp",
    "klagefristUker",
    "antallUttaksperioder",
    "uttaksaktiviteter",
    "utbetalingsperioder",
    "inkludereBeregning"
  ],
  "$defs": {
    "uttaksperiode": {
      "type": "object",
      "required": [
        "periodeFom",
        "periodeTom",
        "utbetalingsgrad"
      ],
      "properties": {
        "periodeFom": {
          "type": "string"
        },
        "periodeTom": {
          "type": "string"
        },
        "utbetalingsgrad": {
          "type": "number"
        }
      }
    },
    "uttaksaktivitet": {
      "type": "object",
      "required": [
        "aktivitetsbeskrivelse",
        "uttaksperioder"
      ],
      "properties": {
        "aktivitetsbeskrivelse": {
          "type": "string"
        },
        "uttaksperioder": {
          "type": "array",
          "items": { "$ref": "#/$defs/uttaksperiode" }
        }
      }
    },
    "utbetalingsperiode": {
      "type": "object",
      "required": [
        "periodeFom",
        "periodeTom",
        "periodeDagsats",
        "utbetaltTilSøker"
      ],
      "properties": {
        "periodeFom": {
          "type": "string"
        },
        "periodeTom": {
          "type": "string"
        },
        "periodeDagsats": {
          "type": "number"
        },
        "utbetaltTilSøker": {
          "type": "number"
        }
      }
    },
    "avslagsperiode": {
      "type": "object",
      "required": [
        "periodeFom",
        "periodeTom",
        "årsak"
      ],
      "properties": {
        "periodeFom": {
          "type": "string"
        },
        "periodeTom": {
          "type": "string"
        },
        "årsak": {
          "type": "string"
        },
        "arbeidsforholdInformasjon": {
          "type": "object",
          "properties":{
            "arbeidsgivernavn": {
              "type": "string"
            },
            "aktivitetType": {
              "type": "string"
            }
          }
        }
      }
    },
    "avslåttAktivitet": {
      "type": "object",
      "required": [
        "årsak",
        "erFL",
        "erSN"
      ],
      "properties": {
        "årsak": {
          "type": "string"
        },
        "arbeidsgiverNavn": {
          "type": "string"
        },
        "erFL": {
          "type": "boolean"
        },
        "erSN": {
          "type": "boolean"
        }
      }
    },
    "arbeidsforhold": {
      "type": "object",
      "required": [
        "arbeidsgiverNavn",
        "månedsinntekt"
      ],
      "properties": {
        "arbeidsgiverNavn": {
          "type": "string"
        },
        "månedsinntekt": {
          "type": "number"
        }
      }
    },
    "selvstendigNæringsdrivende": {
      "type": "object",
      "required": [
        "nyoppstartet",
        "årsinntekt",
        "sistLignedeÅr",
        "inntektLavere_AT_SN",
        "inntektLavere_AT_FL_SN",
        "inntektLavere_FL_SN"
      ],
      "properties": {
        "nyoppstartet": {
          "type": "boolean"
        },
        "årsinntekt": {
          "type": "number"
        },
        "sistLignedeÅr": {
          "type": "number"
        },
        "inntektLavere_AT_SN": {
          "type": "boolean"
        },
        "inntektLavere_AT_FL_SN": {
          "type": "boolean"
        },
        "inntektLavere_FL_SN": {
          "type": "boolean"
        }
      }
    },
    "frilanser": {
      "type": "object",
      "required": [
        "månedsinntekt"
      ],
      "properties": {
        "månedsinntekt": {
          "type": "number"
        }
      }
    },
    "naturalytelse": {
      "type": "object",
      "required": [
        "status",
        "endringsdato",
        "nyDagsats",
        "arbeidsgiverNavn"
      ],
      "properties": {
        "status": {
          "type": "string",
          "enum": [ "TILKOMMER", "BORTFALLER" ]
        },
        "endringsdato": {
          "type": "string"
        },
        "nyDagsats": {
          "type": "number"
        },
        "arbeidsgiverNavn": {
          "type": "string"
        }
      }
    }
  },
  "properties": {
    "felles": {
      "$ref": "file:content/templates/schema_felles.json"
    },
    "revurdering": {
      "type": "boolean"
    },
    "endretFraAvslag": {
      "type": "boolean"
    },
    "utbetalingEndret": {
      "type": "boolean"
    },
    "termindatoEndret": {
      "type": "boolean"
    },
    "refusjonTilBruker": {
      "type": "boolean"
    },
    "antallRefusjonerTilArbeidsgivere": {
      "type": "number"
    },
    "stønadsperiodeTom": {
      "type": "string"
    },
    "månedsbeløp": {
      "type": "number"
    },
    "mottattDato": {
      "type": "string"
    },
    "klagefristUker": {
      "type": "number"
    },
    "antallUttaksperioder": {
      "type": "number"
    },
    "uttaksaktiviteter": {
      "type": "array",
      "items": { "$ref": "#/$defs/uttaksaktivitet" }
    },
    "utbetalingsperioder": {
      "type": "array",
      "items": { "$ref": "#/$defs/utbetalingsperiode" }
    },
    "avslagsperioder": {
      "type": "array",
      "items": { "$ref": "#/$defs/avslagsperiode" }
    },
    "avslåtteAktiviteter": {
      "type": "array",
      "items": { "$ref": "#/$defs/avslåttAktivitet" }
    },
    "inkludereBeregning": {
      "type": "boolean"
    },
    "arbeidsforhold": {
      "type": "array",
      "items": { "$ref": "#/$defs/arbeidsforhold" }
    },
    "selvstendigNæringsdrivende": {
      "$ref": "#/$defs/selvstendigNæringsdrivende"
    },
    "frilanser": {
      "$ref": "#/$defs/frilanser"
    },
    "naturalytelser": {
      "type": "array",
      "items": { "$ref": "#/$defs/naturalytelse" }
    },
    "bruttoBeregningsgrunnlag": {
      "type": "number"
    },
    "militærSivil": {
      "type": "boolean"
    },
    "inntektOver6G": {
      "type": "boolean"
    },
    "seksG": {
      "type": "number"
    },
    "lovhjemmel": {
      "type": "string"
    }
  }
}

=== navikt/fp-dokgen/content/templates/svangerskapspenger-innvilgelse/testdata/test_revurdering_at_fl.json
{
  "felles": {
    "søkerNavn": "Dolly Duck",
    "søkerPersonnummer": "300220 12345",
    "fritekst": "FRITEKST",
    "brevDato": "4. mai 2021",
    "erAutomatiskBehandlet": false,
    "saksnummer": "123456789",
    "ytelseType": "SVP",
    "behandlesAvKA": false,
    "erUtkast": false
  },
  "revurdering": true,
  "endretFraAvslag": false,
  "utbetalingEndret": false,
  "termindatoEndret": true,
  "refusjonTilBruker": true,
  "antallRefusjonerTilArbeidsgivere": 0,
  "stønadsperiodeTom": "31. juli 2021",
  "månedsbeløp": 15000,
  "mottattDato": "1. juli 2021",
  "klagefristUker": 6,
  "antallUttaksperioder": 1,
  "uttaksaktiviteter": [
    {
      "aktivitetsbeskrivelse": "Arbeidsgiver 1 AS",
      "uttaksperioder": [
        {
          "periodeFom": "1. juli 2021",
          "periodeTom": "12. juli 2021",
          "utbetalingsgrad": 100.0
        }
      ]
    }
  ],
  "utbetalingsperioder": [
    {
      "periodeFom": "1. juli 2021",
      "periodeTom": "12. juli 2021",
      "periodeDagsats": 500,
      "utbetaltTilSøker": 200
    }
  ],
  "inkludereBeregning": true,
  "arbeidsforhold":  [
    {
      "arbeidsgiverNavn": "Arbeidsgiver 1 AS",
      "månedsinntekt": 15003
    }
  ],
  "frilanser": {
    "månedsinntekt": 1000
  },
  "bruttoBeregningsgrunnlag": 500000,
  "militærSivil": false,
  "inntektOver6G": false,
  "seksG": 600000,
  "lovhjemmel": "§ 14-4"
}

=== navikt/fp-dokgen/content/templates/svangerskapspenger-innvilgelse/testdata/test_fgb_2_at_1_periode_hver.json
{
  "felles": {
    "søkerNavn": "Dolly Duck",
    "søkerPersonnummer": "300220 12345",
    "brevDato": "4. mai 2021",
    "erAutomatiskBehandlet": false,
    "saksnummer": "123456789",
    "ytelseType": "SVP",
    "behandlesAvKA": false,
    "erUtkast": false
  },
  "revurdering": false,
  "endretFraAvslag": false,
  "utbetalingEndret": false,
  "termindatoEndret": false,
  "refusjonTilBruker": false,
  "antallRefusjonerTilArbeidsgivere": 2,
  "stønadsperiodeTom": "31. juli 2021",
  "månedsbeløp": 15000,
  "mottattDato": "1. juli 2021",
  "klagefristUker": 6,
  "antallUttaksperioder": 2,
  "uttaksaktiviteter": [
    {
      "aktivitetsbeskrivelse": "Arbeidsgiver 1 AS",
      "uttaksperioder": [
        {
          "periodeFom": "1. juli 2021",
          "periodeTom": "12. juli 2021",
          "utbetalingsgrad": 50.0
        }
      ]
    },
    {
      "aktivitetsbeskrivelse": "Arbeidsgiver 2 AS",
      "uttaksperioder": [
        {
          "periodeFom": "20. juli 2021",
          "periodeTom": "31. juli 2021",
          "utbetalingsgrad": 100.0
        }
      ]
    }
  ],
  "utbetalingsperioder": [
    {
      "periodeFom": "1. juli 2021",
      "periodeTom": "12. juli 2021",
      "periodeDagsats": 500,
      "utbetaltTilSøker": 200
    },
    {
      "periodeFom": "20. juli 2021",
      "periodeTom": "31. juli 2021",
      "periodeDagsats": 1000,
      "utbetaltTilSøker": 600
    }
  ],
  "inkludereBeregning": false
}
