=== navikt/fp-dokgen/src/main/resources/content/templates/foreldrepenger-annullert/schema.json
{
  "$id": "urn:no:nav:fpdokgen:foreldrepenger-annullert",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "description": "Dokumentdata for brev Foreldrepenger annullert",
  "type": "object",
  "required": [
    "felles",
    "harSøktOmNyPeriode",
    "klagefristUker"
  ],
  "properties": {
    "felles": {
      "$ref": "classpath:content/templates/schema_felles.json"
    },
    "harSøktOmNyPeriode": {
      "type": "boolean"
    },
    "planlagtOppstartDato": {
      "type": "string"
    },
    "annulleringÅrsak": {
      "type": "string",
      "enum": [
        "BRUKER_HAR_SØKT_OM_NY_PERIODE",
        "BRUKER_MOTTAR_PLEIEPENGER",
        "ANNEN_PART_OVERTAR_UTTAKET",
        "MANUELL_SAKSBEHANDLING"
      ]
    },
    "klagefristUker": {
      "type": "number"
    }
  }
}

=== navikt/fp-dokgen/content/templates/foreldrepenger-annullert/testdata/test_fp_annullert_pga_innvilget_pleiepenger.json
{
  "felles": {
    "søkerNavn": "Dolly Duck",
    "søkerPersonnummer": "300220 12345",
    "brevDato": "4. mai 2021",
    "erAutomatiskBehandlet": true,
    "saksnummer": "123456789",
    "erUtkast": false
  },
  "harSøktOmNyPeriode": false,
  "klagefristUker": 6,
  "annulleringÅrsak": "BRUKER_MOTTAR_PLEIEPENGER"
}

=== navikt/fp-dokgen/src/test/resources/testdata/foreldrepenger-annullert/input/test_fp_annullert_pga_søknad_fra_bruker.json
{
  "felles": {
    "søkerNavn": "Dolly Duck",
    "søkerPersonnummer": "300220 12345",
    "brevDato": "4. mai 2021",
    "erAutomatiskBehandlet": true,
    "saksnummer": "123456789",
    "erUtkast": false
  },
  "harSøktOmNyPeriode": true,
  "planlagtOppstartDato": "1. april 2022",
  "klagefristUker": 6
}
