=== navikt/fp-dokgen/content/templates/innhente-opplysninger/schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "object",
  "title": "The Root Schema",
  "required": [
    "felles",
    "førstegangsbehandling",
    "revurdering",
    "endringssøknad",
    "død",
    "klage"
  ],
  "properties": {
    "felles": {
      "type": "object"
    },
    "førstegangsbehandling": {
      "type": "boolean"
    },
    "revurdering": {
      "type": "boolean"
    },
    "endringssøknad": {
      "type": "boolean"
    },
    "død": {
      "type": "boolean"
    },
    "klage": {
      "type": "boolean"
    },
    "søknadDato": {
      "type": "string"
    },
    "fristDato": {
      "type": "string"
    },
    "dokumentListe": {
      "type": "array"
    }
  }
}

=== navikt/fp-dokgen/content/templates/innhente-opplysninger/testdata/test_es_klage_død.json
{
  "felles": {
    "søkerNavn": "Dolly Duck",
    "søkerPersonnummer": "300220 12345",
    "fritekst" : "FRITEKST",
    "brevDato": "4. april 2020",
    "erKopi" : false,
    "harVerge" : false,
    "saksnummer" : "123456789",
    "ytelseType" : "ES"
  },
  "førstegangsbehandling": false,
  "revurdering": false,
  "endringssøknad": false,
  "død": true,
  "klage": true,
  "søknadDato": "1. april 2020",
  "fristDato": "24. mai 2020",
  "dokumentListe": ["Attest", "Bekreftelse"]
}

=== navikt/fp-dokgen/content/templates/innhente-opplysninger/testdata/test_fp_fgb.json
{
  "felles": {
    "søkerNavn": "Dolly Duck",
    "søkerPersonnummer": "300220 12345",
    "fritekst" : "FRITEKST",
    "brevDato": "4. april 2020",
    "erKopi" : false,
    "harVerge" : false,
    "saksnummer" : "123456789",
    "ytelseType" : "FP"
  },
  "førstegangsbehandling": true,
  "revurdering": false,
  "endringssøknad": false,
  "død": false,
  "klage": false,
  "søknadDato": "1. april 2020",
  "fristDato": "24. mai 2020",
  "dokumentListe": ["Attest", "Bekreftelse"]
}
