=== navikt/fp-dokgen/content/templates/foreldrepenger-annullert/schema.json
{
  "$id": "foreldrepenger-annullert",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "Dokumentdata for brev Foreldrepenger annullert",
  "type": "object",
  "required": [
    "felles",
    "harSøktOmNyPeriode",
    "klagefristUker"
  ],
  "properties": {
    "felles": {
      "$ref": "file:content/templates/schema_felles.json"
    },
    "harSøktOmNyPeriode": {
      "type": "boolean"
    },
    "planlagtOppstartDato": {
      "type": "string"
    },
    "kanBehandlesDato": {
      "type": "string"
    },
    "klagefristUker": {
      "type": "number"
    }
  }
}

=== navikt/fp-dokgen/content/templates/foreldrepenger-annullert/testdata/test_fp_annullert.json
{
  "felles": {
    "søkerNavn": "Dolly Duck",
    "søkerPersonnummer": "300220 12345",
    "brevDato": "4. mai 2021",
    "erAutomatiskBehandlet": true,
    "saksnummer": "123456789",
    "erUtkast": false
  },
  "harSøktOmNyPeriode": true,
  "planlagtOppstartDato": "1. april 2022",
  "kanBehandlesDato": "1. mars 2021",
  "klagefristUker": 6
}
