=== navikt/fp-dokgen/content/templates/svangerskapspenger-avslag/schema.json
{
  "$id": "svangerskapspenger-avslag",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "Dokumentdata for brev Svangerskapspenger avslag",
  "type": "object",
  "required": [
    "felles",
    "årsak",
    "erSøkerDød",
    "antallArbeidsgivere",
    "lovhjemmel",
    "klagefristUker"
  ],
  "properties": {
    "felles": {
      "$ref": "file:content/templates/schema_felles.json"
    },
    "årsak": {
      "type": "string"
    },
    "erSøkerDød": {
      "type": "boolean"
    },
    "stønadsdatoFom": {
      "type": "string"
    },
    "mottattDato": {
      "type": "string"
    },
    "antallArbeidsgivere": {
      "type": "number"
    },
    "halvG": {
      "type": "number"
    },
    "lovhjemmel": {
      "type": "string"
    },
    "klagefristUker": {
      "type": "number"
    }
  }
}

=== navikt/fp-dokgen/content/templates/svangerskapspenger-avslag/testdata/bruker_er_ikke_medlem.json
{
  "felles": {
    "søkerNavn": "Dolly Duck",
    "søkerPersonnummer": "300220 12345",
    "brevDato": "4. mai 2021",
    "erAutomatiskBehandlet": true,
    "saksnummer": "123456789",
    "behandlesAvKA": false,
    "erUtkast": false
  },
  "årsak": "1023",
  "erSøkerDød": false,
  "stønadsdatoFom": "1. april 2021",
  "mottattDato": "23. mars 2021",
  "antallArbeidsgivere": 2,
  "halvG": 50000,
  "lovhjemmel":"§ 14-4",
  "klagefristUker": 6
}
